### ISSUE TITLE
On this link if you go to Test topic 19 july 2021 https://canonizer.com/topic/267-Test-topic-19-july-2021/1-Agreement and click on supported camp Test Camp 2 then link is broken as topic title is not coming in the url.

### ISSUE THREAD

**Issue by gautamv16** [the-canonizer/Canonizer-Beta--Issue-Tracking#157] opened 2023-01-09 07:45 UTC
https://canonizer.com/user/supports/351?topicnum=572&campnum=4&namespace=19

@rupali  on this link if you go to [Test topic 19 july 2021](https://canonizer.com/topic/267-Test-topic-19-july-2021/1-Agreement) and click on supported camp Test Camp 2 then link is broken as topic title is not coming in the url.

**Comment by nalwa** [comment] 2023-01-10 05:28
@rupalichavan9860  as discussed in meting  we are able to find the root cause of issue for which we have separate tocket now - https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/issues/158

So can we close this issue, as it was related to incorrect data record due parent change scenario which we have  found now and we are working on it.

**Comment by rupalichavan9860** [comment] 2023-01-10 05:36
Okay . Closing this

**Closed as completed by rupalichavan9860** 2023-01-10 05:36 UTC
