### ISSUE TITLE
Score update functionality is not working approprately

### ISSUE THREAD

**Issue by SandeepTalentelgia** [the-canonizer/Canonizer-Beta--Issue-Tracking#356] opened 2023-05-23 07:07 UTC
Steps to reproduce:

1.Login with any user on the staging server.
2. Click on browse and select sandbox testing in "select Canon" field.
3. Search the topics / camp in the search having one supporter.
4. Remove the support and check the same by searching again.

Expected Result: it should shows the single support of his own.
Actual Result: Now it shows 2 supports, refer screenshort.
![Screenshot (17)](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/129028750/9107ba61-5d97-40b5-a152-f69f9126d93c)
![Screenshot (16)](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/129028750/9af3c089-5d90-4c8d-bd54-d014a96134ef)

**Comment by sajid315** [comment] 2023-05-31 07:28
@SandeepTalentelgia I have checked the same on staging also as discussed in call with you. We are unable to reproduce this issue. Let me know if it occurs again, also you can close this ticket now.
Thanks

**Comment by rupalichavan9860** [comment] 2023-06-08 01:12
Unable to reproduce so closing this

**Comment by SandeepTalentelgia** [comment] 2023-06-14 05:07
Closed

**Closed as completed** 2023-06-14 16:22 UTC
Labels: bug
