### ISSUE TITLE
Camps appear twice on the supported camps page, and the score for the second choice is incorrect.

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#156] opened 2023-01-09 03:19 UTC
Please refer topic /camp :

https://canonizer.com/topic/88-Theories-of-Consciousness/27-Coded-Ordered-Water

![image](https://user-images.githubusercontent.com/40416610/211235959-b16e9a92-6f71-48e7-ae23-9eedd9b818dd.png)

![image](https://user-images.githubusercontent.com/40416610/211235981-16905a52-1166-413c-b954-924ef2ed94ad.png)

**Comment by rupalichavan9860** [comment] 2023-01-18 05:50
Working fine on staging and live. So closing this ticket

**Comment by rupalichavan9860** [comment] 2023-03-06 03:35
@nalwa Again facing same issue for the same topic. Can you please check ?
Please refer below URL and screenshot : 
https://canonizer.com/user/supports/55?topicnum=88&campnum=&namespace=1 
![image](https://user-images.githubusercontent.com/40416610/223013847-b9aa67d6-21e4-43bc-91e4-539e4dada303.png)

**Comment by nalwa** [comment] 2023-03-07 05:51
@rupalichavan9860  i am not able to reproduce this in both direct and delegate support case.  Is there any particular scenario?

**Comment by karun0607gautam** [comment] 2023-06-03 08:08
this is working fine now so closing

**Closed as completed by karun0607gautam** 2023-06-03 08:08 UTC
Labels: bug

**Comment by rupalichavan9860** [comment] 2023-10-06 13:55
This is working fine now on live so closing this
