### ISSUE TITLE
On direct supporter popup, it shows "Not agreed" username twice on live server.

### ISSUE THREAD

**Issue by sandeeptlgt** [the-canonizer/Canonizer-Beta--Issue-Tracking#502] opened 2023-09-15 08:42 UTC
Steps to reproduce:
1. login with user A on live.
2. User A is the camp supporter.
3. User B archived the camp and commit the changes.
4.  User A didn't approve the change.
5. Click on i icon and check the direct supporter popup.

Actual result: it shows "Not agreed" username twice. 
Expected result: it should not show the name twice on the popup.

Refer screenshot.
![screenbud-3e85145b-6d42-490a-ab4d-5fc9ec3977db](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/108800065/cb5713ff-d10f-41bc-92df-b3c9dcfcf087)

**Comment by rupalichavan9860** [comment] 2023-09-15 13:07
Already  reported #500

**Comment by nalwa** [comment] 2023-09-26 10:55
@rupalichavan9860  and @sandeeptlgt  its a duplicate of 500 and it is fied in that PR, hence i moved it to "In Review" card

**Comment by sandeeptlgt** [comment] 2023-10-09 06:04
Closed, verified on Dev

**Closed as completed** 2024-02-01 07:59 UTC
Labels: bug, duplicate
