### ISSUE TITLE
Some times "Loading page" appears for a moment when we are navigating the web pages.

### ISSUE THREAD

**Issue by akashgit77** [the-canonizer/Canonizer-Beta--Issue-Tracking#867] opened 2024-03-12 08:34 UTC
![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/105647543/35ac11f6-38a0-4990-b422-05caa264c8be)

**Comment by saniatg** [comment] 2024-03-12 09:45
Duplicate of https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/issues/859

**Closed as completed by saniatg** 2024-03-12 09:45 UTC

**Comment by DevAlchemyCD** [comment] 2024-04-08 10:57
@akashgit77  not works on production

**Comment by DevAlchemyCD** [comment] 2024-04-08 11:03
Pr for production : https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1694

**Comment by saniatg** [comment] 2024-05-08 13:33
working fine on production
