### ISSUE TITLE
It allows the user to search the Archived camps

### ISSUE THREAD

**Issue by SandeepTalentelgia** [the-canonizer/Canonizer-Beta--Issue-Tracking#355] opened 2023-05-23 06:53 UTC
Steps to reproduce:

1.Login with any user on the staging server.
2. Click on browse and select sandbox testing in "select Canon" field.
3. Search Archived topics in the search field, without selecting the checkbox "Show archived camps".

Expected Result: it should not allows the user to search the Archived Camps/Topics without selecting the checkbox "Show archived camps".
Actual Result: Now it shows the Archived Camps
![Screenshot (15)](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/129028750/de0fb587-8df8-4c2e-b5aa-09764405305f)
![Screenshot (14)](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/129028750/df81aab1-3877-4026-add2-5f08804e726b)

**Comment by SidhantUppalSyantaq** [comment] 2023-05-29 13:01
@SandeepTalentelgia  it is same as #323

**Comment by vikasranatalentelgia** [comment] 2023-05-30 03:39
@SandeepTalentelgia it is same as #323

**Comment by rupalichavan9860** [comment] 2023-06-01 15:02
@vikasranatalentelgia @SandeepTalentelgia When the user does not select "Show archived camps," it no longer displays archived camps; however, when the user selects "Show archived camps," it no longer displays archived topics.
Please refer attached screenshot : 
Topic Detail Page : 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/65a23d49-80f7-4104-84b2-2a406ae1b6f7)

Browse Page : 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/605c25d3-bffb-452d-80c7-ef8549a040bb)

**Comment by rupalichavan9860** [comment] 2023-06-08 20:06
Last commented issue is not fixed

**Comment by rupalichavan9860** [comment] 2023-06-22 17:05
Duplicate of #323 so closing this

**Closed as completed by rupalichavan9860** 2023-06-22 17:05 UTC
Labels: bug

**Comment by SandeepTalentelgia** [comment] 2023-09-14 08:08
Closed
