### ISSUE TITLE
Sign Petition button must be disabled for archived camp

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#1231] opened 2024-09-04 12:48 UTC
Sign Petition button is enabled 
![image](https://github.com/user-attachments/assets/b8086ce9-711a-4829-8e46-f7eebd6ee3da)

And getting bellow error on button click ,
![image](https://github.com/user-attachments/assets/97cb6b16-4c70-4914-8046-619ecce7d9db)

**Comment by saniatg** [comment] 2024-09-04 17:27
Duplicate of https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/issues/1213

**Closed as completed by saniatg** 2024-09-04 17:27 UTC
Labels: bug
